version: '3.9'

services:
  server:
    image: docker.io/devmaxwel/yolobackend:1.0.1
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - yolo-network
  
  client:
    image: docker.io/devmaxwel/yoloclient:1.0.1
    ports:
      - "3000:3000"
    networks:
      - yolo-network
    depends_on:
      - server
networks:
  yolo-network:
    driver: bridge
  