- name: Configure Application - Clone Repo, Create Vagrant VM, and Set up App in Containers
  hosts: all
  become: true

  vars:
    app_repository: "https://github.com/devmaxwel/yolo.git"
    app_branch: "main"
    app_root_dir: "/vagrant/app"
    vm_name: "myappvm"
    vm_box: "ubuntu/20.04"
    vm_network_ip: "192.168.33.10"
    role_name: "devmaxwel"

  tasks:
    - name: Clone App Repository from GitHub
      git:
        repo: "{{ app_repository }}"
        dest: "{{ app_root_dir }}"
        version: "{{ app_branch }}"

    - name: Install Docker and Docker Compose
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and Install Docker-CE
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Build and Run Docker Containers (Client, Backend)
      command: docker compose up -d
      args:
        chdir: "{{ app_root_dir }}"

    - name: Test if App is Accessible from Browser
      uri:
        url: "http://{{ vm_network_ip }}:3000"
        return_content: yes
        status_code: 200
      register: app_response

    - name: Display App Response
      debug:
        var: app_response.content
