# declarative to deploy server and its Service
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: yolobackend
          image: devmaxwel/yolobackend:1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret-uri
                  key: MONGODB_URI

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: yolobacked-service
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
